angular.module('addressbook').factory('AddressBook', function($http) {

  var addressbok = [
    {
      "id": 1,
      "name": {'firstname':'Glover','lastname':'Baldwin' },
      "phoneno": 8194443126,
      "address":{
        'street'  : '738 Ovington Court',
        'state'   : 'Utah',
        'city'    : 'Soudan',
        'zipcode' : 471400,
        'country' : "Cote D\"Ivoire"
      }
    },
    {
      "id": 2,
      "name": {'firstname':'Ila','lastname':'Donovan' },
      "phoneno": 9684342873,
      "address":{
        'street'  : '589 Jaffray Street',
        'state'   : 'South Carolina',
        'city'    : 'Hollins',
        'zipcode' : 800000,
        'country' : 'Puerto Rico'
      }
    },
    {
      "id": 3,
      "name": {'firstname':'Sandra','lastname':'Ward' },
      "phoneno": 8005122674,
      "address":{
        'street'  : '627 Minna Street',
        'state'   : 'Colorado',
        'city'    : 'Orin',
        'zipcode' : 644100,
        'country' : 'Germany'
      }
    },
    {
      "id": 4,
      "name": {'firstname':'Eve','lastname':'Hensley' },
      "phoneno": 8055352753,
      "address":{
        'street'  : '959 Greenwood Avenue',
        'state'   : 'Guam',
        'city'    : 'Wanship',
        'zipcode' : 645300,
        'country' : 'Argentina'
      }
    },
    {
      "id": 5,
      "name": {'firstname':'Sherry','lastname':'Rosa' },
      "phoneno": 8385152524,
      "address":{
        'street'  : '877 Bushwick Court',
        'state'   : 'Idaho',
        'city'    : 'Roberts',
        'zipcode' : 927500,
        'country' : 'Niger'
      }
    },
    {
      "id": 6,
      "name": {'firstname':'Rhodes','lastname':'Sharpe' },
      "phoneno": 8155453854,
      "address":{
        'street'  : '420 Hanover Place',
        'state'   : 'Massachusetts',
        'city'    : 'Shepardsville',
        'zipcode' : 978000,
        'country' : 'Chad'
      }
    },
    {
      "id": 7,
      "name": {'firstname':'Rosario','lastname':'Swanson' },
      "phoneno": 9985323875,
      "address":{
        'street'  : '530 Nevins Street',
        'state'   : 'Washington',
        'city'    : 'Hall',
        'zipcode' : 100400,
        'country' : 'Ireland'
      }
    },
    {
      "id": 8,
      "name": {'firstname':'Frazier','lastname':'Obrien' },
      "phoneno": 8254103897,
      "address":{
        'street'  : '570 Revere Place',
        'state'   : 'Connecticut',
        'city'    : 'Freeburn',
        'zipcode' : 628600,
        'country' : 'Tokelau'
      }
    },
    {
      "id": 9,
      "name": {'firstname':'Odom','lastname':'Blackwell' },
      "phoneno": 8494773756,
      "address":{
        'street'  : '565 Campus Place',
        'state'   : 'Kansas',
        'city'    : 'Grill',
        'zipcode' : 751200,
        'country' : 'Cyprus'
      }
    },
    {
      "id": 10,
      "name": {'firstname':'Jacquelyn','lastname':'Woods' },
      "phoneno": 8095313112,
      "address":{
        'street'  : '276 Harwood Place',
        'state'   : 'Indiana',
        'city'    : 'Cashtown',
        'zipcode' : 364500,
        'country' : 'China'
      }
    }
  ];

  var countryNames = [
    {"name": "Afghanistan"},
    {"name": "Åland Islands"},
    {"name": "Albania"},
    {"name": "Algeria"},
    {"name": "American Samoa"},
    {"name": "AndorrA"},
    {"name": "Angola"},
    {"name": "Anguilla"},
    {"name": "Antarctica"},
    {"name": "Antigua and Barbuda"},
    {"name": "Argentina"},
    {"name": "Armenia"},
    {"name": "Aruba"},
    {"name": "Australia"},
    {"name": "Austria"},
    {"name": "Azerbaijan"},
    {"name": "Bahamas"},
    {"name": "Bahrain"},
    {"name": "Bangladesh"},
    {"name": "Barbados"},
    {"name": "Belarus"},
    {"name": "Belgium"},
    {"name": "Belize"},
    {"name": "Benin"},
    {"name": "Bermuda"},
    {"name": "Bhutan"},
    {"name": "Bolivia"},
    {"name": "Bosnia and Herzegovina"},
    {"name": "Botswana"},
    {"name": "Bouvet Island"},
    {"name": "Brazil"},
    {"name": "British Indian Ocean Territory"},
    {"name": "Brunei Darussalam"},
    {"name": "Bulgaria"},
    {"name": "Burkina Faso"},
    {"name": "Burundi"},
    {"name": "Cambodia"},
    {"name": "Cameroon"},
    {"name": "Canada"},
    {"name": "Cape Verde"},
    {"name": "Cayman Islands"},
    {"name": "Central African Republic"},
    {"name": "Chad"},
    {"name": "Chile"},
    {"name": "China"},
    {"name": "Christmas Island"},
    {"name": "Cocos (Keeling) Islands"},
    {"name": "Colombia"},
    {"name": "Comoros"},
    {"name": "Congo"},
    {"name": "Congo, The Democratic Republic of the"},
    {"name": "Cook Islands"},
    {"name": "Costa Rica"},
    {"name": "Cote D\"Ivoire"},
    {"name": "Croatia"},
    {"name": "Cuba"},
    {"name": "Cyprus"},
    {"name": "Czech Republic"},
    {"name": "Denmark"},
    {"name": "Djibouti"},
    {"name": "Dominica"},
    {"name": "Dominican Republic"},
    {"name": "Ecuador"},
    {"name": "Egypt"},
    {"name": "El Salvador"},
    {"name": "Equatorial Guinea"},
    {"name": "Eritrea"},
    {"name": "Estonia"},
    {"name": "Ethiopia"},
    {"name": "Falkland Islands (Malvinas)"},
    {"name": "Faroe Islands"},
    {"name": "Fiji"},
    {"name": "Finland"},
    {"name": "France"},
    {"name": "French Guiana"},
    {"name": "French Polynesia"},
    {"name": "French Southern Territories"},
    {"name": "Gabon"},
    {"name": "Gambia"},
    {"name": "Georgia"},
    {"name": "Germany"},
    {"name": "Ghana"},
    {"name": "Gibraltar"},
    {"name": "Greece"},
    {"name": "Greenland"},
    {"name": "Grenada"},
    {"name": "Guadeloupe"},
    {"name": "Guam"},
    {"name": "Guatemala"},
    {"name": "Guernsey"},
    {"name": "Guinea"},
    {"name": "Guinea-Bissau"},
    {"name": "Guyana"},
    {"name": "Haiti"},
    {"name": "Heard Island and Mcdonald Islands"},
    {"name": "Holy See (Vatican City State)"},
    {"name": "Honduras"},
    {"name": "Hong Kong"},
    {"name": "Hungary"},
    {"name": "Iceland"},
    {"name": "India"},
    {"name": "Indonesia"},
    {"name": "Iran, Islamic Republic Of"},
    {"name": "Iraq"},
    {"name": "Ireland"},
    {"name": "Isle of Man"},
    {"name": "Israel"},
    {"name": "Italy"},
    {"name": "Jamaica"},
    {"name": "Japan"},
    {"name": "Jersey"},
    {"name": "Jordan"},
    {"name": "Kazakhstan"},
    {"name": "Kenya"},
    {"name": "Kiribati"},
    {"name": "Korea, Democratic People\"S Republic of"},
    {"name": "Korea, Republic of"},
    {"name": "Kuwait"},
    {"name": "Kyrgyzstan"},
    {"name": "Lao People\"S Democratic Republic"},
    {"name": "Latvia"},
    {"name": "Lebanon"},
    {"name": "Lesotho"},
    {"name": "Liberia"},
    {"name": "Libyan Arab Jamahiriya"},
    {"name": "Liechtenstein"},
    {"name": "Lithuania"},
    {"name": "Luxembourg"},
    {"name": "Macao"},
    {"name": "Macedonia, The Former Yugoslav Republic of"},
    {"name": "Madagascar"},
    {"name": "Malawi"},
    {"name": "Malaysia"},
    {"name": "Maldives"},
    {"name": "Mali"},
    {"name": "Malta"},
    {"name": "Marshall Islands"},
    {"name": "Martinique"},
    {"name": "Mauritania"},
    {"name": "Mauritius"},
    {"name": "Mayotte"},
    {"name": "Mexico"},
    {"name": "Micronesia, Federated States of"},
    {"name": "Moldova, Republic of"},
    {"name": "Monaco"},
    {"name": "Mongolia"},
    {"name": "Montserrat"},
    {"name": "Morocco"},
    {"name": "Mozambique"},
    {"name": "Myanmar"},
    {"name": "Namibia"},
    {"name": "Nauru"},
    {"name": "Nepal"},
    {"name": "Netherlands"},
    {"name": "Netherlands Antilles"},
    {"name": "New Caledonia"},
    {"name": "New Zealand"},
    {"name": "Nicaragua"},
    {"name": "Niger"},
    {"name": "Nigeria"},
    {"name": "Niue"},
    {"name": "Norfolk Island"},
    {"name": "Northern Mariana Islands"},
    {"name": "Norway"},
    {"name": "Oman"},
    {"name": "Pakistan"},
    {"name": "Palau"},
    {"name": "Palestinian Territory, Occupied"},
    {"name": "Panama"},
    {"name": "Papua New Guinea"},
    {"name": "Paraguay"},
    {"name": "Peru"},
    {"name": "Philippines"},
    {"name": "Pitcairn"},
    {"name": "Poland"},
    {"name": "Portugal"},
    {"name": "Puerto Rico"},
    {"name": "Qatar"},
    {"name": "Reunion"},
    {"name": "Romania"},
    {"name": "Russian Federation"},
    {"name": "RWANDA"},
    {"name": "Saint Helena"},
    {"name": "Saint Kitts and Nevis"},
    {"name": "Saint Lucia"},
    {"name": "Saint Pierre and Miquelon"},
    {"name": "Saint Vincent and the Grenadines"},
    {"name": "Samoa"},
    {"name": "San Marino"},
    {"name": "Sao Tome and Principe"},
    {"name": "Saudi Arabia"},
    {"name": "Senegal"},
    {"name": "Serbia and Montenegro"},
    {"name": "Seychelles"},
    {"name": "Sierra Leone"},
    {"name": "Singapore"},
    {"name": "Slovakia"},
    {"name": "Slovenia"},
    {"name": "Solomon Islands"},
    {"name": "Somalia"},
    {"name": "South Africa"},
    {"name": "South Georgia and the South Sandwich Islands"},
    {"name": "Spain"},
    {"name": "Sri Lanka"},
    {"name": "Sudan"},
    {"name": "Suriname"},
    {"name": "Svalbard and Jan Mayen"},
    {"name": "Swaziland"},
    {"name": "Sweden"},
    {"name": "Switzerland"},
    {"name": "Syrian Arab Republic"},
    {"name": "Taiwan, Province of China"},
    {"name": "Tajikistan"},
    {"name": "Tanzania, United Republic of"},
    {"name": "Thailand"},
    {"name": "Timor-Leste"},
    {"name": "Togo"},
    {"name": "Tokelau"},
    {"name": "Tonga"},
    {"name": "Trinidad and Tobago"},
    {"name": "Tunisia"},
    {"name": "Turkey"},
    {"name": "Turkmenistan"},
    {"name": "Turks and Caicos Islands"},
    {"name": "Tuvalu"},
    {"name": "Uganda"},
    {"name": "Ukraine"},
    {"name": "United Arab Emirates"},
    {"name": "United Kingdom"},
    {"name": "United States"},
    {"name": "United States Minor Outlying Islands"},
    {"name": "Uruguay"},
    {"name": "Uzbekistan"},
    {"name": "Vanuatu"},
    {"name": "Venezuela"},
    {"name": "Viet Nam"},
    {"name": "Virgin Islands, British"},
    {"name": "Virgin Islands, U.S."},
    {"name": "Wallis and Futuna"},
    {"name": "Western Sahara"},
    {"name": "Yemen"},
    {"name": "Zambia"},
    {"name": "Zimbabwe"}
  ];

  return {

    getallAddress : function() {
        return addressbok;
    },

    getcountryNames : function() {
      return countryNames;
    }

  }

});


